### PR TITLE
Minor improvements.

### PR DESCRIPTION
**Pull request by niwinz**
The version tools is removed because it is yet an other dependency to install before install anillo. A proper way is set version manually or using any other technique. As manual versioning is not so bad, at this moment I have replaced it with the manual approach.

### CODE REVIEW

**Comment by jespino** [comment]
Can you rebase it?

**Comment by niwinz** [comment]
yes, i'm doing it...

**Comment by niwinz** [comment]
Done.

**Comment by jespino** [comment]
Thanks!! :sparkles:

**Comment by niwinz** [comment]
I'm playing a little bit with anillo so maybe I will send you other minor improvements ;)

**Pull request merged**
